// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WinTools.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WinTools {

  /// <summary>Holder for reflection information generated from WinTools.proto</summary>
  public static partial class WinToolsReflection {

    #region Descriptor
    /// <summary>File descriptor for WinTools.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WinToolsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5XaW5Ub29scy5wcm90bxIIV2luVG9vbHMiWgoHTWVzc2FnZRIYChBGb3Jl",
            "Z3JvdW5kV2luZG93GAEgASgFEhQKDEZpbGVEcm9wTGlzdBgCIAMoCRIPCgdJ",
            "c1Bhc3RlGAMgASgIEg4KBlN0YXR1cxgEIAEoCDKoAgoMR3JwY1NlcnZpY2Vz",
            "EiwKBFBpbmcSES5XaW5Ub29scy5NZXNzYWdlGhEuV2luVG9vbHMuTWVzc2Fn",
            "ZRI7ChNHZXRGb3JlZ3JvdW5kV2luZG93EhEuV2luVG9vbHMuTWVzc2FnZRoR",
            "LldpblRvb2xzLk1lc3NhZ2USNwoPR2V0RmlsZURyb3BMaXN0EhEuV2luVG9v",
            "bHMuTWVzc2FnZRoRLldpblRvb2xzLk1lc3NhZ2USNwoPU2V0RmlsZURyb3BM",
            "aXN0EhEuV2luVG9vbHMuTWVzc2FnZRoRLldpblRvb2xzLk1lc3NhZ2USOwoT",
            "U2V0Rm9yZWdyb3VuZFdpbmRvdxIRLldpblRvb2xzLk1lc3NhZ2UaES5XaW5U",
            "b29scy5NZXNzYWdlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WinTools.Message), global::WinTools.Message.Parser, new[]{ "ForegroundWindow", "FileDropList", "IsPaste", "Status" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Message : pb::IMessage<Message>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Message> _parser = new pb::MessageParser<Message>(() => new Message());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Message> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WinTools.WinToolsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Message() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Message(Message other) : this() {
      foregroundWindow_ = other.foregroundWindow_;
      fileDropList_ = other.fileDropList_.Clone();
      isPaste_ = other.isPaste_;
      status_ = other.status_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Message Clone() {
      return new Message(this);
    }

    /// <summary>Field number for the "ForegroundWindow" field.</summary>
    public const int ForegroundWindowFieldNumber = 1;
    private int foregroundWindow_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ForegroundWindow {
      get { return foregroundWindow_; }
      set {
        foregroundWindow_ = value;
      }
    }

    /// <summary>Field number for the "FileDropList" field.</summary>
    public const int FileDropListFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_fileDropList_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> fileDropList_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> FileDropList {
      get { return fileDropList_; }
    }

    /// <summary>Field number for the "IsPaste" field.</summary>
    public const int IsPasteFieldNumber = 3;
    private bool isPaste_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsPaste {
      get { return isPaste_; }
      set {
        isPaste_ = value;
      }
    }

    /// <summary>Field number for the "Status" field.</summary>
    public const int StatusFieldNumber = 4;
    private bool status_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Message);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Message other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ForegroundWindow != other.ForegroundWindow) return false;
      if(!fileDropList_.Equals(other.fileDropList_)) return false;
      if (IsPaste != other.IsPaste) return false;
      if (Status != other.Status) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ForegroundWindow != 0) hash ^= ForegroundWindow.GetHashCode();
      hash ^= fileDropList_.GetHashCode();
      if (IsPaste != false) hash ^= IsPaste.GetHashCode();
      if (Status != false) hash ^= Status.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ForegroundWindow != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ForegroundWindow);
      }
      fileDropList_.WriteTo(output, _repeated_fileDropList_codec);
      if (IsPaste != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsPaste);
      }
      if (Status != false) {
        output.WriteRawTag(32);
        output.WriteBool(Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ForegroundWindow != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ForegroundWindow);
      }
      fileDropList_.WriteTo(ref output, _repeated_fileDropList_codec);
      if (IsPaste != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsPaste);
      }
      if (Status != false) {
        output.WriteRawTag(32);
        output.WriteBool(Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ForegroundWindow != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ForegroundWindow);
      }
      size += fileDropList_.CalculateSize(_repeated_fileDropList_codec);
      if (IsPaste != false) {
        size += 1 + 1;
      }
      if (Status != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Message other) {
      if (other == null) {
        return;
      }
      if (other.ForegroundWindow != 0) {
        ForegroundWindow = other.ForegroundWindow;
      }
      fileDropList_.Add(other.fileDropList_);
      if (other.IsPaste != false) {
        IsPaste = other.IsPaste;
      }
      if (other.Status != false) {
        Status = other.Status;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ForegroundWindow = input.ReadInt32();
            break;
          }
          case 18: {
            fileDropList_.AddEntriesFrom(input, _repeated_fileDropList_codec);
            break;
          }
          case 24: {
            IsPaste = input.ReadBool();
            break;
          }
          case 32: {
            Status = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ForegroundWindow = input.ReadInt32();
            break;
          }
          case 18: {
            fileDropList_.AddEntriesFrom(ref input, _repeated_fileDropList_codec);
            break;
          }
          case 24: {
            IsPaste = input.ReadBool();
            break;
          }
          case 32: {
            Status = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
